"""/init (IC-802): scan the workspace and (re)write IRONCORE.md project memory.

IRONCORE.md at the workspace root (SPEC §11.1) is injected into the system
prompt so the model never rediscovers how to build, test, or navigate the
project. ``/init`` detects the project type from marker files, writes the
generated sections (overview / build / verify / structure / conventions), and
PRESERVES the user-owned region — everything between the
``<!-- IRONCORE:USER start -->`` and ``<!-- IRONCORE:USER end -->`` sentinels —
across re-runs. ``/memory`` (IC-807) reads this file and appends to that same
region.

Integration: the generated ``## Verify`` section is written in the exact shape
``ironcore.core.verify.CommandVerifier`` parses (bullet-listed command lines
under a ``## Verify`` heading), so the test command ``/init`` detects is the
command the engine actually runs after mutations. It is only written when a
test command is detected — otherwise the verifier's own auto-detection stands.

This is all fast local filesystem work: ``/init`` runs INLINE (no provider, no
``schedule``). This module also owns the IRONCORE.md format helpers that
``memorycmd`` reuses.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from ironcore.commands._helpers import resolve_workspace
from ironcore.commands.base import CommandContext, SlashCommand

#: Workspace-root filename for project memory (SPEC §11.1).
IRONCORE_MD = "IRONCORE.md"

#: Sentinels delimiting the user-editable region /init preserves and /memory appends to.
USER_START = "<!-- IRONCORE:USER start -->"
USER_END = "<!-- IRONCORE:USER end -->"

_GENERATED_NOTICE = (
    "<!-- Generated by /init. Edit the User notes section below; "
    "re-running /init refreshes everything else and keeps your notes. -->"
)

_DEFAULT_USER_BODY = (
    "_Your notes live here. `/init` preserves this section on re-run and "
    "`/memory add <text>` appends to it._"
)

#: Directories a shallow structure map never descends into or lists.
_IGNORE_DIRS = frozenset(
    {
        ".git", ".ironcore", ".hg", ".svn", "__pycache__", "node_modules", ".venv",
        "venv", "env", "target", "dist", "build", ".mypy_cache", ".ruff_cache",
        ".pytest_cache", ".idea", ".vscode", ".tox", ".next", ".turbo",
    }
)

#: Cap on structure-map entries so a huge repo root stays readable.
_MAX_STRUCTURE = 24


@dataclass
class ProjectInfo:
    """What ``detect_project`` found. Pure data; no side effects."""

    languages: list[str] = field(default_factory=list)
    markers: list[str] = field(default_factory=list)
    build_commands: list[str] = field(default_factory=list)
    test_commands: list[str] = field(default_factory=list)
    structure: list[str] = field(default_factory=list)


# -- detection ----------------------------------------------------------------


def _isf(ws: Path, name: str) -> bool:
    return (ws / name).is_file()


def _isd(ws: Path, name: str) -> bool:
    return (ws / name).is_dir()


def _uses_uv(ws: Path) -> bool:
    if _isf(ws, "uv.lock"):
        return True
    try:
        text = (ws / "pyproject.toml").read_text(encoding="utf-8")
    except OSError:
        return False
    return "[tool.uv]" in text or "[tool.uv." in text


def _npm_scripts(ws: Path) -> set[str] | None:
    """Names of ``scripts`` in package.json; ``None`` if it cannot be read."""
    try:
        data = json.loads((ws / "package.json").read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    scripts = data.get("scripts") if isinstance(data, dict) else None
    if not isinstance(scripts, dict):
        return set()
    return {k for k in scripts if isinstance(k, str)}


def detect_project(ws: Path) -> ProjectInfo:
    """Detect languages, build/test commands, and markers from workspace files.

    Pure and side-effect-free (reads marker files only). Recognizes Python,
    Node.js, Rust, and Go, with a Makefile build fallback. ``structure`` is left
    empty here and filled by :func:`structure_map` at write time.
    """
    info = ProjectInfo()

    py_markers = [
        n
        for n in ("pyproject.toml", "setup.py", "setup.cfg", "requirements.txt", "pytest.ini")
        if _isf(ws, n)
    ]
    if py_markers or _isd(ws, "tests"):
        info.languages.append("Python")
        info.markers.extend(py_markers)
        if _uses_uv(ws):
            info.build_commands.append("uv sync")
        elif _isf(ws, "requirements.txt"):
            info.build_commands.append("pip install -r requirements.txt")
        elif _isf(ws, "pyproject.toml") or _isf(ws, "setup.py"):
            info.build_commands.append("pip install -e .")
        if _isf(ws, "pyproject.toml") or _isf(ws, "pytest.ini") or _isd(ws, "tests"):
            info.test_commands.append("pytest -q")

    if _isf(ws, "package.json"):
        info.languages.append("Node.js")
        info.markers.append("package.json")
        scripts = _npm_scripts(ws)
        if scripts is not None:
            info.build_commands.append("npm run build" if "build" in scripts else "npm install")
            if "test" in scripts:
                info.test_commands.append("npm test")

    if _isf(ws, "Cargo.toml"):
        info.languages.append("Rust")
        info.markers.append("Cargo.toml")
        info.build_commands.append("cargo build")
        info.test_commands.append("cargo test")

    if _isf(ws, "go.mod"):
        info.languages.append("Go")
        info.markers.append("go.mod")
        info.build_commands.append("go build ./...")
        info.test_commands.append("go test ./...")

    if _isf(ws, "Makefile") and not info.build_commands:
        info.markers.append("Makefile")
        info.build_commands.append("make")

    return info


def structure_map(ws: Path) -> list[str]:
    """A shallow (top-level) map of the workspace as markdown bullet lines."""
    try:
        entries = sorted(ws.iterdir(), key=lambda p: p.name.lower())
    except OSError:
        return []
    dirs: list[str] = []
    files: list[str] = []
    for path in entries:
        name = path.name
        if name.startswith("."):
            continue  # dotfiles/dotdirs stay out of the map
        if path.is_dir():
            if name in _IGNORE_DIRS:
                continue
            dirs.append(f"- {name}/")
        elif path.is_file():
            files.append(f"- {name}")
    return (dirs + files)[:_MAX_STRUCTURE]


# -- IRONCORE.md format (shared with memorycmd) -------------------------------


def extract_user_section(text: str) -> str | None:
    """The body between the USER sentinels, or ``None`` if they are absent."""
    start = text.find(USER_START)
    end = text.find(USER_END)
    if start == -1 or end == -1 or end < start:
        return None
    return text[start + len(USER_START) : end].strip("\n")


def set_user_section(text: str, new_body: str) -> str:
    """Return ``text`` with the USER-section body replaced by ``new_body``.

    If the sentinels are missing, a fresh sentinel-wrapped section is appended.
    """
    block = f"{USER_START}\n{new_body}\n{USER_END}"
    start = text.find(USER_START)
    end = text.find(USER_END)
    if start == -1 or end == -1 or end < start:
        prefix = text if not text or text.endswith("\n") else text + "\n"
        return f"{prefix}\n{block}\n"
    return text[:start] + block + text[end + len(USER_END) :]


def render_ironcore_md(ws: Path, info: ProjectInfo, user_body: str) -> str:
    """Render the full IRONCORE.md text for a detected project + preserved notes."""
    title = ws.name or str(ws)
    lines: list[str] = [
        f"# {title} — IronCore project memory",
        "",
        _GENERATED_NOTICE,
        "",
        "## Overview",
        "",
        f"- Languages: {', '.join(info.languages) or 'none recognized'}",
        f"- Markers: {', '.join(info.markers) or 'none detected'}",
        "",
        "## Build",
        "",
    ]
    lines += [f"- `{c}`" for c in info.build_commands] or ["- _none detected_"]
    if info.test_commands:
        # Written in CommandVerifier's parse shape: bullets only under this heading.
        lines += ["", "## Verify", ""]
        lines += [f"- `{c}`" for c in info.test_commands]
    lines += ["", "## Structure", ""]
    lines += info.structure or ["- _empty workspace_"]
    lines += [
        "",
        "## Conventions",
        "",
        "- _Record build/lint/style conventions in the User notes below._",
        "",
        USER_START,
        user_body if user_body.strip() else _DEFAULT_USER_BODY,
        USER_END,
        "",
    ]
    return "\n".join(lines)


# -- handler ------------------------------------------------------------------


def _cmd_init(ctx: CommandContext, args: str) -> str:
    ws = resolve_workspace(ctx)
    if ws is None:
        ws = Path.cwd()
    md_path = ws / IRONCORE_MD

    existed = md_path.is_file()
    preserved_body = ""
    if existed:
        try:
            preserved_body = extract_user_section(md_path.read_text(encoding="utf-8")) or ""
        except OSError:
            preserved_body = ""

    info = detect_project(ws)
    info.structure = structure_map(ws)
    content = render_ironcore_md(ws, info, preserved_body)
    try:
        md_path.write_text(content, encoding="utf-8", newline="\n")
    except OSError as exc:
        return f"Could not write {IRONCORE_MD}: {exc}"

    verb = "Refreshed" if existed else "Created"
    note = " (kept your User notes)" if existed and preserved_body else ""
    return (
        f"{verb} {IRONCORE_MD}{note}\n"
        f"- Languages: {', '.join(info.languages) or 'none recognized'}\n"
        f"- Build: {', '.join(info.build_commands) or 'none'}\n"
        f"- Test: {', '.join(info.test_commands) or 'none'}\n"
        f"- Structure: {len(info.structure)} top-level entr"
        f"{'y' if len(info.structure) == 1 else 'ies'} mapped"
    )


COMMANDS: tuple[SlashCommand, ...] = (
    SlashCommand("init", "scan the repo and generate IRONCORE.md", "/init", _cmd_init),
)
